name: solar_engine
description: "A galgame engine made by cmach_socket.Aiming be a cross-platform engine , including desktop and mobile platforms, it also consider of the perform usage.Powered by flutter/dart."
publish_to: 'none'
version: 0.5.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  sidebarx:
  logging:
  path_provider: 
  path:
  animated_text_kit: 
  audioplayers: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/scenario/
    - assets/characters/
    - assets/default/
